# Generated by Django 2.1.5 on 2019-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('localidad', models.CharField(choices=[('-', 'DESCONOCIDA'), ('Z', 'ZARAGOZA'), ('T', 'TERUEL'), ('H', 'HUESCA'), ('A', 'LA ALMUNIA')], default='-', max_length=1)),
                ('url', models.URLField(default='http://unizar.es')),
            ],
        ),
    ]
