# Generated by Django 2.1.5 on 2019-02-06 09:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de Centro')),
                ('nombre', models.CharField(max_length=250)),
                ('localidad', models.CharField(choices=[('-', 'DESCONOCIDA'), ('Z', 'ZARAGOZA'), ('T', 'TERUEL'), ('H', 'HUESCA'), ('A', 'LA ALMUNIA')], default='-', max_length=1)),
                ('url', models.URLField(default='http://unizar.es', verbose_name='Página web del centro')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de entrega')),
                ('titulo', models.CharField(max_length=500)),
                ('resumen', models.CharField(max_length=5000)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de Estudio')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.IntegerField(choices=[(5, 'Grado'), (6, 'Máster')])),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('2017', '2017/2018'), ('2018', '2018/2019')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='NIP UNIZAR')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de Plan')),
                ('curso', models.CharField(choices=[('2017', '2017/2018'), ('2018', '2018/2019')], max_length=4)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Centro')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Estudio')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='planes',
            field=models.ManyToManyField(through='envio.Matricula', to='envio.Plan'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Persona'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Plan'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='centros',
            field=models.ManyToManyField(through='envio.Plan', to='envio.Centro'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Matricula'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('curso', 'persona', 'plan')},
        ),
    ]
