# Generated by Django 2.1.5 on 2019-01-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.IntegerField(choices=[(5, 'Grado'), (6, 'Máster')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('curso', models.CharField(choices=[('2018', '2018/2019')], max_length=4)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Centro')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Estudio')),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='centros',
            field=models.ManyToManyField(default=5, through='envio.Plan', to='envio.Centro'),
        ),
    ]
