# Generated by Django 2.1.5 on 2019-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0002_auto_20190123_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='tipo',
            field=models.IntegerField(choices=[(5, 'Grado'), (6, 'Máster')]),
        ),
    ]
