# Generated by Django 2.1.5 on 2019-02-08 17:36

import django.core.validators
from django.db import migrations, models
import envio.models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0002_auto_20190206_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Tuitions'},
        ),
        migrations.AddField(
            model_name='entrega',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to=envio.models.user_upload_anexos_directory_path),
        ),
        migrations.AddField(
            model_name='entrega',
            name='memoria',
            field=models.FileField(default=None, upload_to=envio.models.user_upload_memoria_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centro',
            name='url',
            field=models.URLField(default='http://unizar.es', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Deposit code'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='eid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Study Program code'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nip',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Plan code'),
        ),
    ]
