# Generated by Django 2.1.5 on 2019-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0004_auto_20190211_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='entrega_material_adicional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrega',
            name='notas',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='resumen_en',
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
