# Generated by Django 2.1.5 on 2019-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0005_auto_20190131_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
