# Generated by Django 2.1.5 on 2019-02-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0005_auto_20190211_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='terminos',
            field=models.BooleanField(default=False),
        ),
    ]
