# Generated by Django 2.1.5 on 2019-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0006_entrega_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de entrega'),
        ),
    ]
