# Generated by Django 2.1.5 on 2019-02-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0008_auto_20190213_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='terminos',
        ),
    ]
