# Generated by Django 2.1.5 on 2019-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0011_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='departamentos',
            field=models.ManyToManyField(to='envio.Departamento'),
        ),
    ]
