# Generated by Django 2.1.5 on 2019-02-14 10:34

from django.db import migrations
import envio.models
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0013_entrega_anexos2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='anexos2',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='anexos',
            field=private_files.models.fields.PrivateFileField(blank=True, null=True, upload_to=envio.models.user_upload_anexos_directory_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='memoria',
            field=private_files.models.fields.PrivateFileField(upload_to=envio.models.user_upload_memoria_directory_path, verbose_name='file'),
        ),
    ]
