# Generated by Django 2.1.5 on 2019-02-14 10:49

from django.db import migrations
import envio.models
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0014_auto_20190214_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='anexos2',
            field=private_files.models.fields.PrivateFileField(blank=True, null=True, upload_to=envio.models.user_upload_anexos_directory_path, verbose_name='anexos2'),
        ),
    ]
