# Generated by Django 2.1.5 on 2019-02-14 11:10

from django.db import migrations, models
import envio.models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0015_entrega_anexos2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to=envio.models.user_upload_anexos_directory_path),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='memoria',
            field=models.FileField(upload_to=envio.models.user_upload_memoria_directory_path),
        ),
    ]
