# Generated by Django 2.1.5 on 2019-02-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0018_auto_20190214_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='ficheroprivado',
        ),
    ]
