# Generated by Django 2.1.5 on 2019-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0021_auto_20190227_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Sin confirmar'), (1, 'Sin validar'), (2, 'Validada'), (3, 'Pasada a Zaguan')], default=0),
        ),
    ]
